# When editing this file, remember that http://www.yamllint.com is your friend :-)
---

driver:
  name: vagrant
  customize:
    memory: 512
    cpus: 1

platforms:
  - name: centos-7.2
    driver_config:
      network:
      - ["private_network", {ip: "192.168.33.93"}]

verifier:
  name: inspec

provisioner:
  name: chef_zero

suites:
  - name: default
  - name: ci
    run_list:
      - recipe[commons_test::artifact_and_maven]
      - recipe[commons::test_prepare]
      - recipe[commons::_mock_files]
      - recipe[commons::awscli]
      - recipe[commons::chef-client-cron]
      - recipe[commons::databags-to-files]
      - recipe[commons::chefzero]
      - recipe[commons::ec2-tagging]
      - recipe[commons::ec2-discovery]
      - recipe[commons::error-pages]
      - recipe[commons::certs]
    data_bags_path: "test/integration/data_bags"
    attributes: {
      "name": "chef-commons-local",
      "hostname": "chef-commons-local",
      "commons" : {
        "install_awscli" : true,
        "logstash" : {
          "ec2" : {
            "run_discovery" : true
          }
        },
        "chef-client-cron" : {
          "cron_name" : "test1",
          "chef_json_cookbook" : "commons",
          "chef_json_source" : "cron/chef-client.cron.erb"
        },
        "awscli" : {
          "credentials_databag" : "aws",
          "credentials_databag_item" : "test"
        },
        "databags_to_files" : {
          "default_destination_folder" : "/etc/ssl/certs",
          "default_filename_prefix" : "mycertname",
          "databags" : {
            "certs" : {
              "test" : {}
            }
          }
        },
        "ec2_discovery" : {
          "skip_ec2_commands" : true,
          "current" : {
            "ip" : "171.1.1.1",
            "az" : "us-east-1a"
          },
          "output" : {
            "elements" : {
              "id" : "InstanceId",
              "ip" : "PrivateIpAddress",
              "state" : "State/Name"
            },
            "tags" : {
              "instance_name" : "Name"
            },
            "filter_in" : {
              "state" : "running"
            }
          }
        }
      },
      artifacts: {
        junit1: {
          enabled: true,
          groupId : "junit",
          artifactId : "junit",
          version : "4.11",
          destination: "/home/vagrant/default_suite",
          owner: "root",
          # Force failure by setting timeout to 1 sec
          # timeout: 1
        },
        junit2: {
          groupId : "junit",
          artifactId : "junit",
          version : "4.11",
          destination: "/home/vagrant/disabled_suite",
          owner: "root"
        },
        junit3: {
          enabled: true,
          unzip: true,
          groupId : "junit",
          artifactId : "junit",
          version : "4.11",
          destination: "/home/vagrant/subfolder_suite",
          subfolder: "META-INF/\\*",
          owner: "root"
        },
        junit4: {
          enabled : true,
          unzip: true,
          groupId : "junit",
          artifactId : "junit",
          version : "4.11",
          destination : "/home/vagrant/properties_suite",
          owner : "root",
          filtering_mode : "replace",
          properties: {
            "META-INF/MANIFEST.MF" : {
              "Manifest-Version" : "555"
              },
            "LICENSE.txt" : {
              "superProperty" : "addition works?",
              filtering_mode : 'append'
              }
          },
          terms: {
            "META-INF/MANIFEST.MF" : {
              '(Oracle Corporation)' : "Test replace Term"
              }
            }
        }
      }
    }
